### ISSUE TITLE
Can not login on the dashboard

### ISSUE THREAD

**Issue by flo-mic** [AIIX/Remote-Services-Dashboard#1]
Hi @AIIX I just saw your dashboard under the OVOS repositories. I would like to test it, but I'm not able to login. Tried several combinations like the os user and password, but the login page is always popping up again.

Also there is no possibility to create an issue under https://github.com/OpenVoiceOS/OVOS-Dashboard that's why I'm opening the issue here. Maybe there is a repository setting missing for the fork.

**Comment by AIIX** [comment]
A new Login Password for OVOS will be generated at the time when the remote dashboard is enabled from the settings menu, you can currently set your own username and password by exporting the following environment variables before starting the flask application.


``` 
export SIMPLELOGIN_USERNAME = "exampleusername"
export SIMPLELOGIN_PASSWORD = "examplepassword"
```

If you would like to test with the default username and password it is currently for only testing purpose set to username "admin" and password "secret"

Will look into fixing that setting for the issues page on the OVOS fork

**Comment by flo-mic** [comment]
ah perfect, thanks fro the fast response ;)
